//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetEuro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaderboard
    {
        public string UserId { get; set; }
        public int Points { get; set; }
        public int ScoreHit { get; set; }
        public int ResultHit { get; set; }
        public int PlacedBets { get; set; }
    
        public virtual User User { get; set; }
    }
}
